import os
import sqlite3
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from app.config import Config
from app.services.database import DatabaseService

class PdfGeneratorService:
    @staticmethod
    def generate_daily_report():
        save_dir = os.path.join(Config.INSPECTION_HISTORY_DIR, 'reports')
        os.makedirs(save_dir, exist_ok=True)
        save_path = os.path.join(save_dir, f"QC_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
        
        # Query DB for today's stats
        conn = DatabaseService.get_connection()
        cursor = conn.cursor()
        today = datetime.now().strftime('%Y-%m-%d')
        
        cursor.execute("SELECT * FROM predictions WHERE date(timestamp) = ?", (today,))
        rows = cursor.fetchall()
        
        total = len(rows)
        fresh = sum(1 for r in rows if r['prediction'] == 'Fresh')
        rotten = sum(1 for r in rows if r['prediction'] == 'Rotten')
        unknown = sum(1 for r in rows if r['prediction'] == 'Unknown')
        
        avg_conf = sum(r['confidence'] for r in rows) / total if total > 0 else 0
        
        doc = SimpleDocTemplate(save_path, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []
        
        # Title
        title_style = ParagraphStyle(
            name='Title', parent=styles['Heading1'], fontSize=28, alignment=1, spaceAfter=10, textColor=colors.HexColor("#004c30")
        )
        subtitle_style = ParagraphStyle(
            name='Subtitle', parent=styles['Heading2'], fontSize=16, alignment=1, spaceAfter=30, textColor=colors.HexColor("#555555")
        )
        
        elements.append(Spacer(1, 50))
        elements.append(Paragraph("QualiVision AI", title_style))
        elements.append(Paragraph("Industrial Quality Control Report", subtitle_style))
        elements.append(Spacer(1, 30))
        
        # Meta info
        meta_data = [
            ['Date:', datetime.now().strftime('%B %d, %Y')],
            ['Shift:', 'Morning Shift'],
            ['Operator:', 'System Admin'],
            ['Model Architecture:', 'EfficientNetV2B0'],
            ['Input Size:', '224x224'],
            ['Model Version:', '1.0.0']
        ]
        
        meta_table = Table(meta_data, colWidths=[150, 250])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor("#333333")),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 30))
        
        # Section 2
        elements.append(Paragraph("Inspection Summary", styles['Heading2']))
        elements.append(Spacer(1, 10))
        
        stats_data = [
            ['Metric', 'Value'],
            ['Total Inspections', str(total)],
            ['Fresh Tomatoes', str(fresh)],
            ['Rejected (Rotten)', str(rotten)],
            ['Unknown / Manual Review', str(unknown)],
            ['Pass Rate', f"{(fresh/total*100) if total > 0 else 0:.1f}%"],
            ['Failure Rate', f"{(rotten/total*100) if total > 0 else 0:.1f}%"],
            ['Unknown Rate', f"{(unknown/total*100) if total > 0 else 0:.1f}%"],
            ['Average Confidence', f"{avg_conf:.1f}%"]
        ]
        
        t = Table(stats_data, colWidths=[250, 150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (1,0), colors.HexColor("#16c784")),
            ('TEXTCOLOR', (0,0), (1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#f4f6f8")),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor("#dddddd")),
            ('FONTNAME', (0,1), (0,-1), 'Helvetica-Bold'),
            ('ALIGN', (0,1), (0,-1), 'LEFT'),
        ]))
        elements.append(t)
        
        elements.append(Spacer(1, 40))
        elements.append(Paragraph("Report auto-generated by QualiVision AI Engine.", styles['Italic']))
        
        doc.build(elements)
        conn.close()
        return save_path
